language: php

php:
- 7.3
- 7.2
- 7.1
- 7.0
- 5.6

matrix:
  fast_finish: true
  include:
    - php: nightly
  allow_failures:
    - php: nightly

sudo: false

install:
- travis_retry composer update --no-interaction --prefer-source

script:
- vendor/bin/phpunit
